
task:
  name: logical_upgrade_demo
  container:
    dockerfile: ci/Dockerfile
  build_script:
      - useradd -s /bin/bash -m pgrunner
      - cp ci/logical_upgrade.sh /home/pgrunner
      - chown pgrunner:pgrunner /home/pgrunner/logical_upgrade.sh
      - su - pgrunner -c '/usr/bin/readlink -f .'
      - su - pgrunner ./logical_ugrade.sh

